print("\n----------------------------")
print("Question 1 : prendre en mail le projet et le code fourni")
print("Découvrir l’ensemble de fichiers et le code fourni. Lancer le code. Une boucle d’affichage est lancée. Décrire ce qu’elle affiche. Quelle est sa condition d’arrêt ?")
print("----------------------------")
print("La boucle d'affichage affiche l'état, l'action, l'état suivant et la récompense à chaque itération.")
print("La condition d'arrêt est atteinte lorsque l'état final est atteint (dans chaque iteration) et que le nombre d'itérations defini est atteint (1000).")
print("----------------------------")
print("Question 2 : Que fait la fonction playEpisode ?")
print("----------------------------")
print("La fonction playEpisode simule une episode de Q-learning. Elle choisit une action (exploration ou exploitation) en fonction de l'epsilon-greedy, met à jour la matrice Q en fonction de la récompense reçue et de l'état suivant, et renvoie la matrice Q mise à jour ainsi que les récompenses totales accumulées.")
print("----------------------------")
print("Question 3 : Que fait la fonction printQ ?")
print("----------------------------")
print("La fonction printQ affiche la matrice Q et les meilleures actions pour chaque état en fonction des valeurs Q.")
print("----------------------------")
print("Question 4 : Que fait la fonction observe_next_state ?")
print("----------------------------")
print("La fonction observe_next_state prend un état et une action en entrée et renvoie l'état suivant résultant de cette action.")
print("----------------------------")
print("Question 5 : Que fait la fonction observe_reward ?")
print("----------------------------")
print("La fonction observe_reward prend un état et une action en entrée et renvoie la récompense associée à cette action dans cet état.")
print("----------------------------")
print("Question 6 : Que fait la fonction isEnd ?")
print("----------------------------")
print("La fonction isEnd prend un état en entrée et renvoie True si cet état est un état final, sinon elle renvoie False.")
print("----------------------------")